# Generated by Django 4.1.3 on 2022-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=80)),
                ('course_id', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=80)),
                ('batch_no', models.CharField(max_length=30)),
                ('standard_Fees', models.FloatField()),
                ('fees_altered', models.CharField(max_length=10)),
                ('fees_alloted', models.FloatField()),
                ('fees_received', models.FloatField()),
                ('fees_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default=None, max_length=20, null=True)),
                ('course', models.CharField(max_length=80, null=True)),
                ('batch_no', models.CharField(max_length=30, null=True)),
                ('standard_Fees', models.FloatField()),
                ('from_date', models.DateField()),
                ('upto_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('mode', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
