# Generated by Django 4.1.3 on 2022-11-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='course',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='standard_Fees',
        ),
        migrations.RemoveField(
            model_name='course',
            name='upto_date',
        ),
    ]
