# Generated by Django 4.1.3 on 2022-11-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0005_course_standard_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=80, null=True)),
                ('from_date', models.DateField()),
                ('upto_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='admissions',
            name='course',
            field=models.CharField(choices=[('Java Developer', 'Java Developer'), ('Python Full Stack Developer', 'Python Full Stack Developer')], max_length=80),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='student_name',
            field=models.CharField(choices=[('Deepak Raghunath Khochare', 'Deepak Raghunath Khochare')], max_length=80),
        ),
    ]
