# Generated by Django 4.1.3 on 2022-11-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0006_batch_remove_admissions_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
