# Generated by Django 4.1.3 on 2022-11-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0008_alter_batch_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='batch_no',
        ),
        migrations.AddField(
            model_name='admissions',
            name='batch_name',
            field=models.CharField(choices=[('AESPYTB01', 'AESPYTB01')], max_length=30, null=True),
        ),
    ]
