# Generated by Django 4.1.3 on 2022-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0009_remove_admissions_batch_no_admissions_batch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='batch_name',
        ),
        migrations.AddField(
            model_name='admissions',
            name='original_batch_name',
            field=models.CharField(choices=[('AESJAVB01', 'AESJAVB01'), ('AESPYTB01', 'AESPYTB01')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='admissions',
            name='present_batch_name',
            field=models.CharField(choices=[('AESJAVB01', 'AESJAVB01'), ('AESPYTB01', 'AESPYTB01')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='fees_allotted',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='fees_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='fees_received',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='standard_Fees',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='student_name',
            field=models.CharField(choices=[('Deepak Raghunath Khochare', 'Deepak Raghunath Khochare'), ('Moreshwar Mahadeo Narvekar', 'Moreshwar Mahadeo Narvekar')], max_length=80),
        ),
    ]
