# Generated by Django 4.1.3 on 2022-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0010_remove_admissions_batch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(default=None, max_length=20, null=True)),
                ('course', models.CharField(max_length=80, null=True)),
                ('batch_name', models.FloatField(null=True)),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('UTR_UPI_No', models.CharField(max_length=50)),
            ],
        ),
    ]
