# Generated by Django 4.1.3 on 2022-11-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0012_rename_batch_name_fees_present_batch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='present_batch_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
