# Generated by Django 4.1.3 on 2022-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0013_alter_fees_present_batch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='Student_name',
            new_name='student_name',
        ),
        migrations.AlterField(
            model_name='fees',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
