# Generated by Django 4.1.3 on 2022-11-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0014_rename_student_name_fees_student_name_alter_fees_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='student_name',
            field=models.CharField(choices=[('ddd', 'ddd'), ('Deepak Raghunath Khochare', 'Deepak Raghunath Khochare'), ('Moreshwar Mahadeo Narvekar', 'Moreshwar Mahadeo Narvekar')], max_length=80),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
