# Generated by Django 4.1.3 on 2022-11-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0015_alter_admissions_student_name_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='fees_allotted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='fees_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='fees_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='standard_Fees',
            field=models.IntegerField(default=0),
        ),
    ]
